src/account/urls.py
from django.conf.urls import patterns, url
from account import forms as account_forms


urlpatterns = patterns(
    '',
    url(r'^login/?$', 'account.views.login', name='login'),
    url(r'^register/?$', 'account.views.register', name='register'),
    url(r'^logout/?$', 'account.views.logout', name='logout'),
    url(r'^choose_username/?$', 'account.views.get_user_details',
        name='get_user_details'),
    url(r'^settings/?$', 'account.views.account_settings', name='settings'),
    url(r'^add_password/?$', 'account.views.add_password',
        name='add_password'),
    url(r'^remove_password/?$', 'account.views.remove_password',
        name='remove_password'),
    url(r'^add_login/?$', 'account.views.add_extra_login',
        name='add_extra_login'),
    url(r'^delete/?$', 'account.views.delete', name='delete_user'),
    # Use Django's built-in password changing and resetting tools.
    url(r'^change_password/?$', 'django.contrib.auth.views.password_change',
        {
            'template_name': 'password_change.html',
            'post_change_redirect': 'settings',
        },
        name='password_change'),
    url(r'^forgot/?$', 'django.contrib.auth.views.password_reset',
        {
            'template_name': 'password_reset.html',
            'email_template_name': 'password_reset_email.html',
            'subject_template_name': 'password_reset_subject.txt',
            'password_reset_form': account_forms.ForgotPasswordForm,
            'from_email': 'noreply@datahub.csail.mit.edu',
        },
        name='password_reset'),
    url(r'^forgot/done/?$',
        'django.contrib.auth.views.password_reset_done',
        {
            'template_name': 'password_reset_done.html',
        },
        name='password_reset_done'),
    url((r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/'
         r'(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/?$'),
        'django.contrib.auth.views.password_reset_confirm',
        {
            'template_name': 'password_reset_confirm.html',
        },
        name='password_reset_confirm'),
    url(r'^reset/done/?$',
        'django.contrib.auth.views.password_reset_complete',
        {
            'template_name': 'password_reset_complete.html',
        },
        name='password_reset_complete'),
    # url(r'^verify/$', 'account.views.verify_email'),
)

src/api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [

    # user
    url(r'^v1/user/?$',
        views.CurrentUser.as_view(),
        name='user'),
    url(r'^v1/user/repos/?$',
        views.CurrentUserRepos.as_view(),
        name='user_repos'),

    # repos
    url(r'^v1/repos/?$',
        views.Repos.as_view(),
        name='repos_all'),
    url(r'^v1/repos/public/?$', views.ReposPublic.as_view(),
        name='repos_public'),
    url(r'^v1/repos/(?P<repo_base>\w+)/?$',
        views.ReposForUser.as_view(),
        name='repos_specific'),
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)/?$',
        views.Repo.as_view(),
        name='repo'),

    # collaborators
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)'
        r'/collaborators/(?P<collaborator>\w+)/?$',
        views.Collaborator.as_view(),
        name='collaborator'),
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)/collaborators/?$',
        views.Collaborators.as_view(),
        name='collaborators'),

    # tables
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)'
        r'/tables/(?P<table>\w+)/?$',
        views.Table.as_view(),
        name='table'),
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)/tables/?$',
        views.Tables.as_view(),
        name='tables'),

    # views
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)/'
        r'views/(?P<view>\w+)/?$',
        views.View.as_view(),
        name='view'),
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)/views/?$',
        views.Views.as_view(),
        name='views'),

    # cards
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)'
        r'/cards/(?P<card_name>\w+)/?$',
        views.Card.as_view(),
        name='card'),
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)/cards/?$',
        views.Cards.as_view(),
        name='cards'),

    # files
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)'
        r'/files/(?P<file_name>[\w\s\.]+)$',
        views.File.as_view(),
        name='file'),
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)/files/?$',
        views.Files.as_view(),
        name='files'),

    # query
    url(r'^v1/query/(?P<repo_base>\w+)/(?P<repo_name>\w+)/?$',
        views.Query.as_view(),
        name='query_with_repo'),
    url(r'^v1/query/(?P<repo_base>\w+)/?$',
        views.Query.as_view(),
        name='query'),

    # row level security
    url(r'^v1/rls/id/(?P<policy_id>\w+)//?$',
        views.RowLevelSecurityById.as_view(),
        name='row_level_security_by_id'),

    url(r'^v1/rls/?$', views.RowLevelSecurity.as_view(),
        name='row_level_security'),
    url(r'^v1/rls/(?P<repo_name>\w+)/?$',
        views.RowLevelSecurity.as_view(),
        name='row_level_security_repo_name'),
    url(r'^v1/rls/(?P<repo_name>\w+)/(?P<table>\w+)/?$',
        views.RowLevelSecurity.as_view(),
        name='row_level_security_table'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

src/apps/dbwipes/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^page/(\w+)/(\w+)/(\w+)/?$', 'dbwipes.views.index'),

    url(r'^api/repos/?$', 'dbwipes.views.repos'),
    url(r'^api/tables/?$', 'dbwipes.views.tables'),
    url(r'^api/schema/?$', 'dbwipes.views.schema'),
    url(r'^api/tuples/?$', 'dbwipes.views.api_tuples'),
    url(r'^api/query/?$', 'dbwipes.views.api_query'),
    url(r'^api/column_distribution/?$', 'dbwipes.views.column_distribution'),
    url(r'^api/column_distributions/?$', 'dbwipes.views.column_distributions'),
    url(r'^api/requestid/?$', 'dbwipes.views.requestid'),
    url(r'^api/status/?$', 'dbwipes.views.api_status'),
    url(r'^api/scorpion/?$', 'dbwipes.views.scorpion'),
    url(r'^api/create_data_cache/$', 'dbwipes.views.create_data_cache'),
)

src/browser/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from views import OAuthAppUpdate


urlpatterns = patterns(
    '',

    # Home Page
    url(r'^$', 'browser.views.home', name='browser-home'),
    url(r'^about$', 'browser.views.about', name='browser-about'),
    url(r'^favicon\.ico$',
        RedirectView.as_view(url='/static/images/favicon.ico',
                             permanent=True)),

    # WWW Pages
    url(r'^www/', include('www.urls', namespace='www')),

    # Account Related
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^account/', include('account.urls')),


    # OAuth Provider
    # override the default app update form
    url(r'^oauth2/applications/(?P<pk>\d+)/update/$',
        OAuthAppUpdate.as_view(), name="update"),
    # override the default app listing page to use /developer/apps
    url(r'^oauth2/applications/$',
        RedirectView.as_view(pattern_name='browser-apps',
                             permanent=True), name="list"),
    url(r'^oauth2/', include('oauth2_provider.urls',
        namespace='oauth2_provider')),


    # API Pages
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls',
        namespace='rest_framework')),
    url(r'^api-docs/', include('rest_framework_swagger.urls')),

    # Thrift Services
    url(r'^service$', 'browser.views.service_core_binary',
        name='browser-thrift_service_binary'),
    url(r'^service/account$', 'browser.views.service_account_binary',
        name='browser-thrift_service_account'),
    url(r'^service/json$', 'browser.views.service_core_json',
        name='browser-thrift_service_json'),


    # Create
    url(r'^create/(\w+)/repo/?$', 'browser.views.repo_create',
        name='browser-repo_create'),
    url(r'^create/(\w+)/(\w+)/card/?$', 'browser.views.card_create',
        name='browser-card_create'),
    url(r'^create/annotation/?$', 'browser.views.create_annotation',
        name='browser-create_annotation'),
    
    ####add by beyhhhh>>>
    url(r'^browse/board/?$', 'browser.views.show_board',
        name='browser-show_board'),
    url(r'^browse/result_show/?$', 'browser.views.result_show',
        name='browser-result_show'),
    url(r'^browse/log_show/?$', 'browser.views.log_show',
        name='browser-log_show'),
    url(r'^browse/accuracy_show/?$', 'browser.views.accuracy_show',
        name='browser-accuracy_show'),
    #url(r'^browse/updata_record_result/?$', 'browser.views.updata_record_result',
    #    name='browser-log_show'),
    ####add by beyhhhh<<<
    # Browse
    url(r'^browse/(\w+)/(\w+)/table/(\w+)/?$', 'browser.views.table',
        name='browser-table'),
    url(r'^browse/(\w+)/(\w+)/query/?$', 'browser.views.query',
        name='browser-query'),
    url(r'^browse/(\w+)/(\w+)/card/(.+)/?$', 'browser.views.card',
        name='browser-card'),
    
    
    ##add by strongman
    
    
    
    url(r'^browse/(\w+)/(\w+)/?$', 'browser.views.repo',
        name='browser-repo'),
    #url(r'^browse/(\w+)/(\w+)/record/?$','browser.views.record',name='browser-record'),
    #url(r'^browse/(\w+)/(\w+)/tables/?$', 'browser.views.repo_tables',name='browser-repo_tables'),
    #url(r'^browse/(\w+)/(\w+)/files/?$', 'browser.views.repo_files',name='browser-repo_files'),
    
    ####>>add by beyhhhh
    ##url(r'^browse/(\w+)/(\w+)/codes/?$', 'browser.views.repo_codes',name='browser-repo_codes'),
    ####<<add by beyhhhh
    
    ##url(r'^browse/(\w+)/(\w+)/cards/?$', 'browser.views.repo_cards',name='browser-repo_cards'),
    
    
    
    ####>>add by beyhhhh
    #url(r'^browse/(\w+)/(\w+)/creat_new_codes/?$', 'browser.views.creat_new_codes',name='browser-creat_new'),
    
    #url(r'^browse/(\w+)/(\w+)/creat_new_data_sets/?$', 'browser.views.creat_new_data_sets',name='browser-creat_new'),
    
    #url(r'^browse/(\w+)/(\w+)/data_code_list_update/?$', 'browser.views.data_code_list_update',name='data_code_list_update'),
    
    #url(r'^browse/(\w+)/(\w+)/Push/?$', 'browser.views.data_code_list_update_github',name='data_code_list_update_github'),
    
    #url(r'^browse/(\w+)/(\w+)/update_file_flord_codes_data/?$', 'browser.views.update_file_flord_codes_data',name='browser-update_file_flord_codes_data'),
    
    #url(r'^browse/(\w+)/(\w+)/jupyter_coding/?$', 'browser.views.jupyter_coding',name='browser-creat_new'),
    
    url(r'^browse/(\w+)/(\w+)/upload_github/?$', 'browser.views.upload_github',name='browser-upload_github'),
    
    url(r'^browse/(\w+)/(\w+)/branch_list/?$', 'browser.views.code_branch_list',
        name='browser-branch_list'),
    
    
    url(r'^browse/(\w+)/(\w+)/(\w+)/commit/?$', 'browser.views.commit_code_watch',name='browser-commit_code_watch'),
    
    url(r'^browse/(\w+)/(\w+)/(\w+)/reset/?$', 'browser.views.reset_project_commit',name='browser-reset_project_commit'),
    
    url(r'^browse/(\w+)/(\w+)/(\w+)/(.+)/run/?$', 'browser.views.run_the_exp',name='browser-run_the_exp'),
    
    url(r'^browse/(\w+)/(\w+)/(.+)/table_show/?$', 'browser.views.table_show',name='browser-table_show'),
    
     url(r'^browse/(\w+)/(\w+)/(.+)/Make_data_set_public/?$', 'browser.views.Make_data_set_public',name='browser-Make_data_set_public'),
    
     url(r'^browse/(\w+)/(\w+)/(.+)/Make_code_public/?$', 'browser.views.Make_code_public',name='browser-Make_code_public'),
    ####<<add by beyhhhh
    

    ####add by beyhhhh>>>
    ####they are the url that add in twice change 
    
    url(r'^browse/(\w+)/add_to_the_repo/creat/?$', 'browser.views.add_to_the_repo', name='browser-add_to_the_repo'),
    
    
    url(r'^browse/public/data_set/?$', 'browser.views.public_data_set', name='browser-public_data_set'),
    
    
    url(r'^browse/(\w+)/(\w+)/add_codes/?$', 'browser.views.add_codes_to_repo',name='browser-add_codes_to_repo'),
    
    
    url(r'^browse/(\w+)/(\w+)/add_datas/?$', 'browser.views.add_datas_to_repo',name='browser-add_datas_to_repo'),
    
    url(r'^browse/(\w+)/(\w+)/move_code_to_repo/?$', 'browser.views.move_code_to_repo',name='browser-move_code_to_repo'),
    
    url(r'^browse/(\w+)/(\w+)/move_data_to_repo/?$', 'browser.views.move_data_to_repo',name='browser-move_data_to_repo'),
    
    ####<<<add by beyhhhh
    url(r'^browse/public/?$', 'browser.views.public_data_set', name='browser-public'),
    
    url(r'^browse/(\w+)/?$', 'browser.views.user', name='browser-user'),
    
    url(r'^browse/?$', 'browser.views.user', name='browser-user-default'),

    url(r'^browse/(\w+)/(\w+)/securitypolicies/(\w+)/?$',
        'browser.views.security_policies', name='browse-security_policies'),




    # Delete
    url(r'^delete/(\w+)/(\w+)/?$', 'browser.views.repo_delete',
        name='browser-repo_delete'),
    url(r'^delete/(\w+)/(\w+)/table/(\w+)/?$', 'browser.views.table_delete',
        name='browser-table_delete'),
    url(r'^delete/(\w+)/(\w+)/view/(\w+)/?$', 'browser.views.view_delete',
        name='browser-view_delete'),
    url(r'^delete/(\w+)/(\w+)/card/(\w+)/?$', 'browser.views.card_delete',
        name='browser-card_delete'),
    url(r'^delete/(\w+)/(\w+)/file/([ -~]+)/?$', 'browser.views.file_delete',
        name='browser-file_delete'),


    # Export
    url(r'^export/(\w+)/(\w+)/table/(\w+)/?$', 'browser.views.table_export',
        name='browser-table_export'),
    url(r'^export/(\w+)/(\w+)/card/(\w+)/?$', 'browser.views.card_export',
        name='browser-card_export'),


    # Special File Operations
    url(r'^upload/(\w+)/(\w+)/file/?$', 'browser.views.file_upload',
        name='browser-file_upload'),
    
    #add bey beyhhhh>>>
    url(r'^upload/(\w+)/(\w+)/code/?$', 'browser.views.code_upload',
        name='browser-code_upload'),
    
    url(r'^upload/(\w+)/(\w+)/data/?$', 'browser.views.data_upload',
        name='browser-data_upload'),
    #<<<add by beyhhhh
    
    url(r'^import/(\w+)/(\w+)/file/([ -~]+)', 'browser.views.file_import',
        name='browser-file_import'),
    url(r'^download/(\w+)/(\w+)/file/([ -~]+)', 'browser.views.file_download'),


    # Settings
    #url(r'^settings/(\w+)/(\w+)/?$','browser.views.repo_settings',name='browser-repo_settings'),


    # Collaborators
    # url(r'^collaborator/repo/(\w+)/(\w+)/add/?$','browser.views.repo_collaborators_add',name='browser-repo_collaborators_add'),

    #url(r'^collaborator/repo/(\w+)/(\w+)/remove/(\w+)/?$','browser.views.repo_collaborators_remove',name='browser-repo_collaborators_remove'),


    # Developer Apps
    url(r'^developer/apps/?$', 'browser.views.apps',
        name='browser-apps'),

    url(r'^developer/apps/detail/(\w+)/?$', 'browser.views.thrift_app_detail',
        name='browser-thrift_app_detail'),

    url(r'^developer/apps/register/?$', 'browser.views.app_register',
        name='browser-app_register'),

    url(r'^developer/apps/remove/(\w+)/?$', 'browser.views.app_remove',
        name='browser-app_remove'),


    # Permissions
    url(r'^permissions/apps/allow_access/(\w+)/(\w+)$',
        'browser.views.app_allow_access',
        name='browser-app_allow_access'),
    url(r'^update_visibility/(\w+)/(\w+)/card/(.+)/?$',
        'browser.views.card_update_public',
        name='browser-card_update_public'),


    # Security Policies
    url(r'^create/(\w+)/(\w+)/(\w+)/securitypolicy/?$',
        'browser.views.security_policy_create', name='security-policy_create'),
    url(r'^edit/(\w+)/(\w+)/(\w+)/securitypolicy/(\w+)/?$',
        'browser.views.security_policy_edit', name='security-policy_edit'),
    url(r'^delete/(\w+)/(\w+)/(\w+)/securitypolicy/(\w+)/?$',
        'browser.views.security_policy_delete',
        name='browser-securitypolicy_delete'),
    url(r'^execute/(\w+)/(\w+)/(\w+)/securitypolicy/query/?$',
        'browser.views.security_policy_query', name='security-policy_query'),



    # Client Apps
    url(r'^apps/console/', include('console.urls', namespace='console')),

src/browser/templates/apps.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
  
  <h4 class="inline-block">
    <a href="{% url 'browser-user' login %}">{{login}}</a> / apps
  </h4>
  
  <hr />
  <br />
  <div class="panel panel-default">
    <div class="table-responsive">
      <table id="oauth_apps" class="table">
        <tr class="panel-default">
          <th colspan="3" class="lead panel-heading">
            OAuth Apps &nbsp;
            <a class="btn btn-default btn-sm" href="{% url 'oauth2_provider:register' %}" title="Register a New DataHub App"><span class="glyphicon glyphicon-plus"></span></a>
            {# <a class="btn btn-default btn-sm" href="/developer/apps/register" title="Register a New DataHub App"><span class="glyphicon glyphicon-plus"></span></a> #}
          </th>
        </tr>
        <tr>
        <th>App Name</th>
        <th>Client ID</th>
        <th></th>
        </tr>          
        {% for app in oauth_apps %}
          <tr>
            <td><a href="{{ app.get_absolute_url }}">{{app.name}}</a></td>
            <td>{{app.client_id}}</td>
            <td></td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="3" class="bg-warning">You don't have any registered apps yet.</strong></td>
            </tr>
        {% endfor %}
        {% if thrift_apps|length > 0 %}
          <tr class="panel-default">
            <th colspan="3" class="lead panel-heading">
              <span class="lead">Thrift Apps</span>
            </th>
          </tr>
          <tr>
            <th>App Name</th>
            <th>App Token</th>
            <th>Date Created</th>
          </tr>
          {% for app in thrift_apps %}
            <tr>
              <td><a href="{% url 'browser-thrift_app_detail' app.app_id %}">{{app.app_name}} (id: {{app.app_id}})</a></td>
              <td>{{app.app_token}}</td>
              <td>{{app.timestamp}}</td>
            </tr>
          {% endfor %}
        {% endif %} 
      </table>
    </div>
  </div>
</div>
{% endblock %}

src/browser/templates/card-browse.html
{% extends "table-browse-template.html" %}
{% block table-name %}
card / {{card.card_name}}
{% endblock %}
{% block apps %}
{% endblock %}

{% block tabs %}
<ul class="nav nav-tabs" role="tablist">
  <li><a href="/browse/{{repo_base}}/{{repo}}/tables" role="tab">Tables &amp; Views</a></li>
  <li><a href="/browse/{{repo_base}}/{{repo}}/files" role="tab">Files</a></li>
  <li class="active"><a href="/browse/{{repo_base}}/{{repo}}/cards" role="tab">Cards</a></li>
</ul>
{% endblock %}


{% block panel-title %}
  <span class="lead">
    {{card.card_name}} &nbsp;
    <a class="btn btn-default btn-sm" href="/browse/{{repo_base}}/{{repo}}/cards" title="Back to All Cards"><span class="glyphicon glyphicon-arrow-left"></span></a>
    {% if card.public %}
    <span
    class="btn btn-default btn-sm modal-link modal-confirm-form-dialog"
    target-modal="#confirm-form-modal"
    target-modal-title="Make Card Private"
    target-modal-body="Make this card private to restrict access to collaborators."
    target-modal-operation="Make Private"
    target-url="{% url 'browser-card_update_public' repo_base repo card.card_name %}"
    target-modal-form-inputs='<input type="hidden" name="public" value="False" />'
    title="Change Visibility">Visibility: Public</span>
    <a href="{% url 'api:card' repo_base=repo_base repo_name=repo card_name=card.card_name format='json' %}"><span class="btn btn-default btn-sm">Public Link</span></a>
    {% else %}
    <span
    class="btn btn-default btn-sm modal-link modal-confirm-form-dialog"
    target-modal="#confirm-form-modal"
    target-modal-title="Make Card Public"
    target-modal-body="Make this card public to allow unauthenticated users to run this query and see its results."
    target-modal-operation="Make Public"
    target-url="{% url 'browser-card_update_public' repo_base repo card.card_name %}"
    target-modal-form-inputs='<input type="hidden" name="public" value="True" />'
    title="Change Visibility">Visibility: Private</span>
    {% endif %}


  </span><br />
  Query: <code class="language-sql" data-lang="sql">{{card.query}}</code><br />
{% endblock %}

{% block annotation %}
  {% if annotation %}
    <span class="text-muted">{{annotation}}</span>&nbsp; &nbsp;<span class="modal-link annotation-modal-dialog" target-modal="#annotation-modal" title="Edit Description" placeholder="{{annotation}}" url-path="/browse/{{repo_base}}/{{repo}}/card/{{card.card_name}}"><span class="glyphicon glyphicon-edit"></span></span>
  {% else %}
    <span class="text-warning"><em>No description yet</em></span>&nbsp; &nbsp;<span class="modal-link annotation-modal-dialog" target-modal="#annotation-modal" title="Add Description" url-path="/browse/{{repo_base}}/{{repo}}/card/{{card.card_name}}"><span class="glyphicon glyphicon-edit"></span></span>
  {% endif %}    
{% endblock %}

{% block table-empty-warning %}
  <p class="bg-warning">The <strong>{{table}}</strong> card is empty.</p>
{% endblock %}

src/browser/templates/data_code_list_update_github.html
{% extends "repo-browse-template.html" %}
{% block tabs %}
<ul class="nav nav-tabs" role="tablist">
  <li><a href="/browse/{{repo_base}}/{{repo}}/tables" role="tab">Tables &amp; Views</a></li>
  <li><a href="/browse/{{repo_base}}/{{repo}}/files" role="tab">Data_sets</a></li>
  <li><a href="/browse/{{repo_base}}/{{repo}}/codes" role="tab">Codes</a></li>
  <li class="active"><a href="/browse/{{repo_base}}/{{repo}}/Push" role="tab">Push_Code</a></li>
  <li><a href="/browse/{{repo_base}}/{{repo}}/cards" role="tab">Cards</a></li>
  <li><a href="/browse/{{repo_base}}/{{repo}}/record" role="tab">Records</a></li>
</ul>
{% endblock %}
{% block tab-content %}

<!--add by beyhhhh-->
<form action="/browse/{{login}}/{{repo}}/upload_github" method="POST">
    {% csrf_token %}
<!--add by beyhhhh-->    
    

<div class="panel panel-default">
  <div class="panel-heading">
    <span class="lead">
      Dataset &nbsp;
    </span>
  </div>

  {% if Data_list and Data_list|length > 0 %}
    <div class="table-responsive">
      <table class="table">
        <tbody>            
          {% for data in Data_list %}
          <tr>
              <td>
              <input type="checkbox" name= "check_box_list" value = "{{data}}"/>
              <a href="/download/{{repo_base}}/{{repo}}/file/{{data}}">{{data}}</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    
  {% else %}
    <p class="bg-warning">No data set in <strong>{{repo_base}}/{{repo}}</strong></p>
  {% endif %} 
  </div>
    
 
 <div class="panel panel-default">
  <div class="panel-heading">
    <span class="lead">
      Code &nbsp;
    </span>
  </div>

  {% if Code_list and Code_list|length > 0 %}
    <div class="table-responsive">
      <table class="table">
        <tbody>            
          {% for code in Code_list %}
          <tr>
              <td>
               <input type="checkbox" name= "check_box_list" value = "{{code}}"/>
              <a href="/download/{{repo_base}}/{{repo}}/file/{{code}}">{{code}}</a>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    
  {% else %}
    <p class="bg-warning">No code in <strong>{{repo_base}}/{{repo}}</strong></p>
  {% endif %} 
  </div>
    
    
<!--add by beyhhhh--->
    <input class="btn btn-primary btn-xsm" type="submit" value="Push Codes">
  </form>
<!--add by beyhhhh--->

{%if Push_result%}
<p class="bg-warning">{{Push_result}}</p>
{%endif%}
{% endblock %}

src/browser/templates/query.html
{% extends "repo-browse-template.html" %}

src/browser/templates/repo-browse-data-shows.html
{% extends "repo-browse-template.html" %}
{% block tabs %}

{% endblock %}

{% block tab-content %}

<div class="container">
<div class="panel panel-default">
  <div class="panel-heading">
    <span class="lead">
      {{data_name}} &nbsp;
    </span>
  </div>

  {% if data and data|length > 0 %}
    <div class="table-responsive">
      <table class="table">
        <tbody>            
          {% for cont in data %}
          <tr>
              {%for con in cont%}
              <td>
                  <a>{{con}}</a>
              </td>
            {% endfor %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    
  {% else %}
    <p class="bg-warning">No data set in <strong>{{repo_base}}/{{repo}}</strong></p>
  {% endif %} 
  </div>


{% endblock %}

src/browser/templates/repo-browse-template.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
  <h4 class="inline-block">
      {%if repo_base%}
    <a class="link" href=/browse/{{repo_base}}>{{repo_base}}</a>
      {%endif%}
      {%if repo%}
      <a class="link" href=/browse/{{repo_base}}/{{repo}}>/ {{repo}}</a>
      {%endif%}
  </h4>

  <hr />
  <br />
  <br />
  {% block tabs %}
  {% endblock %}
  <br />

  <script>    
    $(document).on("click", "#btn-dataq", function(e) {    
      e.preventDefault();    
      DataQ.DQ("{{repo}}", function(query) {   
        $("#txt-sql").val(query);    
      });    
    });    
  </script>

  {% block tab-content %}
  {% endblock %}
{% endblock %}