src/api/urls.py
from django.conf.urls import url
from rest_framework.urlpatterns import format_suffix_patterns
from . import views

urlpatterns = [

    # user
    url(r'^v1/user/?$',
        views.CurrentUser.as_view(),
        name='user'),
    url(r'^v1/user/repos/?$',
        views.CurrentUserRepos.as_view(),
        name='user_repos'),

    # repos
    url(r'^v1/repos/?$',
        views.Repos.as_view(),
        name='repos_all'),
    url(r'^v1/repos/public/?$', views.ReposPublic.as_view(),
        name='repos_public'),
    url(r'^v1/repos/(?P<repo_base>\w+)/?$',
        views.ReposForUser.as_view(),
        name='repos_specific'),
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)/?$',
        views.Repo.as_view(),
        name='repo'),

    # collaborators
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)'
        r'/collaborators/(?P<collaborator>\w+)/?$',
        views.Collaborator.as_view(),
        name='collaborator'),
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)/collaborators/?$',
        views.Collaborators.as_view(),
        name='collaborators'),

    # tables
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)'
        r'/tables/(?P<table>\w+)/?$',
        views.Table.as_view(),
        name='table'),
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)/tables/?$',
        views.Tables.as_view(),
        name='tables'),

    # views
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)/'
        r'views/(?P<view>\w+)/?$',
        views.View.as_view(),
        name='view'),
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)/views/?$',
        views.Views.as_view(),
        name='views'),

    # cards
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)'
        r'/cards/(?P<card_name>\w+)/?$',
        views.Card.as_view(),
        name='card'),
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)/cards/?$',
        views.Cards.as_view(),
        name='cards'),

    # files
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)'
        r'/files/(?P<file_name>[\w\s\.]+)$',
        views.File.as_view(),
        name='file'),
    url(r'^v1/repos/(?P<repo_base>\w+)/(?P<repo_name>\w+)/files/?$',
        views.Files.as_view(),
        name='files'),

    # query
    url(r'^v1/query/(?P<repo_base>\w+)/(?P<repo_name>\w+)/?$',
        views.Query.as_view(),
        name='query_with_repo'),
    url(r'^v1/query/(?P<repo_base>\w+)/?$',
        views.Query.as_view(),
        name='query'),

    # row level security
    url(r'^v1/rls/id/(?P<policy_id>\w+)//?$',
        views.RowLevelSecurityById.as_view(),
        name='row_level_security_by_id'),

    url(r'^v1/rls/?$', views.RowLevelSecurity.as_view(),
        name='row_level_security'),
    url(r'^v1/rls/(?P<repo_name>\w+)/?$',
        views.RowLevelSecurity.as_view(),
        name='row_level_security_repo_name'),
    url(r'^v1/rls/(?P<repo_name>\w+)/(?P<table>\w+)/?$',
        views.RowLevelSecurity.as_view(),
        name='row_level_security_table'),
]

urlpatterns = format_suffix_patterns(urlpatterns)

src/apps/dbwipes/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    '',
    url(r'^page/(\w+)/(\w+)/(\w+)/?$', 'dbwipes.views.index'),

    url(r'^api/repos/?$', 'dbwipes.views.repos'),
    url(r'^api/tables/?$', 'dbwipes.views.tables'),
    url(r'^api/schema/?$', 'dbwipes.views.schema'),
    url(r'^api/tuples/?$', 'dbwipes.views.api_tuples'),
    url(r'^api/query/?$', 'dbwipes.views.api_query'),
    url(r'^api/column_distribution/?$', 'dbwipes.views.column_distribution'),
    url(r'^api/column_distributions/?$', 'dbwipes.views.column_distributions'),
    url(r'^api/requestid/?$', 'dbwipes.views.requestid'),
    url(r'^api/status/?$', 'dbwipes.views.api_status'),
    url(r'^api/scorpion/?$', 'dbwipes.views.scorpion'),
    url(r'^api/create_data_cache/$', 'dbwipes.views.create_data_cache'),
)

src/browser/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.views.generic.base import RedirectView
from views import OAuthAppUpdate


urlpatterns = patterns(
    '',

    # Home Page
    url(r'^$', 'browser.views.home', name='browser-home'),
    url(r'^about$', 'browser.views.about', name='browser-about'),
    url(r'^favicon\.ico$',
        RedirectView.as_view(url='/static/images/favicon.ico',
                             permanent=True)),

    # WWW Pages
    url(r'^www/', include('www.urls', namespace='www')),

    # Account Related
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^account/', include('account.urls')),


    # OAuth Provider
    # override the default app update form
    url(r'^oauth2/applications/(?P<pk>\d+)/update/$',
        OAuthAppUpdate.as_view(), name="update"),
    # override the default app listing page to use /developer/apps
    url(r'^oauth2/applications/$',
        RedirectView.as_view(pattern_name='browser-apps',
                             permanent=True), name="list"),
    url(r'^oauth2/', include('oauth2_provider.urls',
        namespace='oauth2_provider')),


    # API Pages
    url(r'^api/', include('api.urls', namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls',
        namespace='rest_framework')),
    url(r'^api-docs/', include('rest_framework_swagger.urls')),

    # Thrift Services
    url(r'^service$', 'browser.views.service_core_binary',
        name='browser-thrift_service_binary'),
    url(r'^service/account$', 'browser.views.service_account_binary',
        name='browser-thrift_service_account'),
    url(r'^service/json$', 'browser.views.service_core_json',
        name='browser-thrift_service_json'),


    # Create
    url(r'^create/(\w+)/repo/?$', 'browser.views.repo_create',
        name='browser-repo_create'),
    url(r'^create/(\w+)/(\w+)/card/?$', 'browser.views.card_create',
        name='browser-card_create'),
    url(r'^create/annotation/?$', 'browser.views.create_annotation',
        name='browser-create_annotation'),
    
    ####add by beyhhhh>>>
    url(r'^browse/board/?$', 'browser.views.show_board',
        name='browser-show_board'),
    url(r'^browse/result_show/?$', 'browser.views.result_show',
        name='browser-result_show'),
    url(r'^browse/log_show/?$', 'browser.views.log_show',
        name='browser-log_show'),
    url(r'^browse/accuracy_show/?$', 'browser.views.accuracy_show',
        name='browser-accuracy_show'),
    #url(r'^browse/updata_record_result/?$', 'browser.views.updata_record_result',
    #    name='browser-log_show'),
    ####add by beyhhhh<<<
    # Browse
    url(r'^browse/(\w+)/(\w+)/table/(\w+)/?$', 'browser.views.table',
        name='browser-table'),
    url(r'^browse/(\w+)/(\w+)/query/?$', 'browser.views.query',
        name='browser-query'),
    url(r'^browse/(\w+)/(\w+)/card/(.+)/?$', 'browser.views.card',
        name='browser-card'),
    
    
    ##add by strongman
    
    
    
    url(r'^browse/(\w+)/(\w+)/?$', 'browser.views.repo',
        name='browser-repo'),
    #url(r'^browse/(\w+)/(\w+)/record/?$','browser.views.record',name='browser-record'),
    #url(r'^browse/(\w+)/(\w+)/tables/?$', 'browser.views.repo_tables',name='browser-repo_tables'),
    #url(r'^browse/(\w+)/(\w+)/files/?$', 'browser.views.repo_files',name='browser-repo_files'),
    
    ####>>add by beyhhhh
    ##url(r'^browse/(\w+)/(\w+)/codes/?$', 'browser.views.repo_codes',name='browser-repo_codes'),
    ####<<add by beyhhhh
    
    ##url(r'^browse/(\w+)/(\w+)/cards/?$', 'browser.views.repo_cards',name='browser-repo_cards'),
    
    
    
    ####>>add by beyhhhh
    #url(r'^browse/(\w+)/(\w+)/creat_new_codes/?$', 'browser.views.creat_new_codes',name='browser-creat_new'),
    
    #url(r'^browse/(\w+)/(\w+)/creat_new_data_sets/?$', 'browser.views.creat_new_data_sets',name='browser-creat_new'),
    
    #url(r'^browse/(\w+)/(\w+)/data_code_list_update/?$', 'browser.views.data_code_list_update',name='data_code_list_update'),
    
    #url(r'^browse/(\w+)/(\w+)/Push/?$', 'browser.views.data_code_list_update_github',name='data_code_list_update_github'),
    
    #url(r'^browse/(\w+)/(\w+)/update_file_flord_codes_data/?$', 'browser.views.update_file_flord_codes_data',name='browser-update_file_flord_codes_data'),
    
    #url(r'^browse/(\w+)/(\w+)/jupyter_coding/?$', 'browser.views.jupyter_coding',name='browser-creat_new'),
    
    url(r'^browse/(\w+)/(\w+)/upload_github/?$', 'browser.views.upload_github',name='browser-upload_github'),
    
    url(r'^browse/(\w+)/(\w+)/branch_list/?$', 'browser.views.code_branch_list',
        name='browser-branch_list'),
    
    
    url(r'^browse/(\w+)/(\w+)/(\w+)/commit/?$', 'browser.views.commit_code_watch',name='browser-commit_code_watch'),
    
    url(r'^browse/(\w+)/(\w+)/(\w+)/reset/?$', 'browser.views.reset_project_commit',name='browser-reset_project_commit'),
    
    url(r'^browse/(\w+)/(\w+)/(\w+)/(.+)/run/?$', 'browser.views.run_the_exp',name='browser-run_the_exp'),
    
    url(r'^browse/(\w+)/(\w+)/(.+)/table_show/?$', 'browser.views.table_show',name='browser-table_show'),
    
     url(r'^browse/(\w+)/(\w+)/(.+)/Make_data_set_public/?$', 'browser.views.Make_data_set_public',name='browser-Make_data_set_public'),
    
     url(r'^browse/(\w+)/(\w+)/(.+)/Make_code_public/?$', 'browser.views.Make_code_public',name='browser-Make_code_public'),
    ####<<add by beyhhhh
    

    ####add by beyhhhh>>>
    ####they are the url that add in twice change 
    
    url(r'^browse/(\w+)/add_to_the_repo/creat/?$', 'browser.views.add_to_the_repo', name='browser-add_to_the_repo'),
    
    
    url(r'^browse/public/data_set/?$', 'browser.views.public_data_set', name='browser-public_data_set'),
    
    
    url(r'^browse/(\w+)/(\w+)/add_codes/?$', 'browser.views.add_codes_to_repo',name='browser-add_codes_to_repo'),
    
    
    url(r'^browse/(\w+)/(\w+)/add_datas/?$', 'browser.views.add_datas_to_repo',name='browser-add_datas_to_repo'),
    
    url(r'^browse/(\w+)/(\w+)/move_code_to_repo/?$', 'browser.views.move_code_to_repo',name='browser-move_code_to_repo'),
    
    url(r'^browse/(\w+)/(\w+)/move_data_to_repo/?$', 'browser.views.move_data_to_repo',name='browser-move_data_to_repo'),
    
    ####<<<add by beyhhhh
    url(r'^browse/public/?$', 'browser.views.public_data_set', name='browser-public'),
    
    url(r'^browse/(\w+)/?$', 'browser.views.user', name='browser-user'),
    
    url(r'^browse/?$', 'browser.views.user', name='browser-user-default'),

    url(r'^browse/(\w+)/(\w+)/securitypolicies/(\w+)/?$',
        'browser.views.security_policies', name='browse-security_policies'),




    # Delete
    url(r'^delete/(\w+)/(\w+)/?$', 'browser.views.repo_delete',
        name='browser-repo_delete'),
    url(r'^delete/(\w+)/(\w+)/table/(\w+)/?$', 'browser.views.table_delete',
        name='browser-table_delete'),
    url(r'^delete/(\w+)/(\w+)/view/(\w+)/?$', 'browser.views.view_delete',
        name='browser-view_delete'),
    url(r'^delete/(\w+)/(\w+)/card/(\w+)/?$', 'browser.views.card_delete',
        name='browser-card_delete'),
    url(r'^delete/(\w+)/(\w+)/file/([ -~]+)/?$', 'browser.views.file_delete',
        name='browser-file_delete'),


    # Export
    url(r'^export/(\w+)/(\w+)/table/(\w+)/?$', 'browser.views.table_export',
        name='browser-table_export'),
    url(r'^export/(\w+)/(\w+)/card/(\w+)/?$', 'browser.views.card_export',
        name='browser-card_export'),


    # Special File Operations
    url(r'^upload/(\w+)/(\w+)/file/?$', 'browser.views.file_upload',
        name='browser-file_upload'),
    
    #add bey beyhhhh>>>
    url(r'^upload/(\w+)/(\w+)/code/?$', 'browser.views.code_upload',
        name='browser-code_upload'),
    
    url(r'^upload/(\w+)/(\w+)/data/?$', 'browser.views.data_upload',
        name='browser-data_upload'),
    #<<<add by beyhhhh
    
    url(r'^import/(\w+)/(\w+)/file/([ -~]+)', 'browser.views.file_import',
        name='browser-file_import'),
    url(r'^download/(\w+)/(\w+)/file/([ -~]+)', 'browser.views.file_download'),


    # Settings
    #url(r'^settings/(\w+)/(\w+)/?$','browser.views.repo_settings',name='browser-repo_settings'),


    # Collaborators
    # url(r'^collaborator/repo/(\w+)/(\w+)/add/?$','browser.views.repo_collaborators_add',name='browser-repo_collaborators_add'),

    #url(r'^collaborator/repo/(\w+)/(\w+)/remove/(\w+)/?$','browser.views.repo_collaborators_remove',name='browser-repo_collaborators_remove'),


    # Developer Apps
    url(r'^developer/apps/?$', 'browser.views.apps',
        name='browser-apps'),

    url(r'^developer/apps/detail/(\w+)/?$', 'browser.views.thrift_app_detail',
        name='browser-thrift_app_detail'),

    url(r'^developer/apps/register/?$', 'browser.views.app_register',
        name='browser-app_register'),

    url(r'^developer/apps/remove/(\w+)/?$', 'browser.views.app_remove',
        name='browser-app_remove'),


    # Permissions
    url(r'^permissions/apps/allow_access/(\w+)/(\w+)$',
        'browser.views.app_allow_access',
        name='browser-app_allow_access'),
    url(r'^update_visibility/(\w+)/(\w+)/card/(.+)/?$',
        'browser.views.card_update_public',
        name='browser-card_update_public'),


    # Security Policies
    url(r'^create/(\w+)/(\w+)/(\w+)/securitypolicy/?$',
        'browser.views.security_policy_create', name='security-policy_create'),
    url(r'^edit/(\w+)/(\w+)/(\w+)/securitypolicy/(\w+)/?$',
        'browser.views.security_policy_edit', name='security-policy_edit'),
    url(r'^delete/(\w+)/(\w+)/(\w+)/securitypolicy/(\w+)/?$',
        'browser.views.security_policy_delete',
        name='browser-securitypolicy_delete'),
    url(r'^execute/(\w+)/(\w+)/(\w+)/securitypolicy/query/?$',
        'browser.views.security_policy_query', name='security-policy_query'),



    # Client Apps
    url(r'^apps/console/', include('console.urls', namespace='console')),

src/templates/oauth2_provider/application_detail.html
{% extends "layout.html" %}

{% block js %}
<script type="text/javascript">
$(document).ready(function() {
  $('#confirmModal').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget)
    var title = button.data('modal-title')
    var body = button.data('modal-body')
    var action = button.data('form-action')
    var modal = $(this)
    modal.find('.modal-title').text(title)
    modal.find('.modal-body').html(body)
    modal.find('.modal-footer form').attr('action', action)
  })
  $('#confirmModal').on('hide.bs.modal', function (argument) {
    var modal = $(this)
    modal.find('.modal-footer form').attr('action', '')
  })
})
</script>  

{% endblock js %}

{% block content %}
<div class="container">
  
  <h4 class="inline-block">
    <a href="{% url 'browser-user' user.get_username %}">{{ user.get_username }}</a> / <a href="{% url 'browser-apps' %}">apps</a>
  </h4>
  
  <hr />
  <br />

  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">OAuth App Details</h3>
      </div>
      <div class="panel-body" style="word-wrap: break-word;">
        <p>
          <label>App Name</label><br />
          <span>{{ application.name }}</span>
        </p>

        <p>
          <label>Client ID</label><br />
          <span>{{ application.client_id }}</span>
        </p>

        <p>
          <label>Client Secret</label><br />
          <span>{{ application.client_secret }}</span>
        </p>

        <p>
          <label>Client Type</label><br />
          <span>{{ application.client_type }}</span>
        </p>

        <p>
          <label>Authorization Grant Type</label><br />
          <span>{{ application.authorization_grant_type }}</span>
        </p>

        {% if application.redirect_uris %}
          <p>
            <label>Redirect URIs</label><br />
            <span>{{ application.redirect_uris|linebreaksbr }}</span>
          </p>
        {% endif %}

        <a class="btn btn-primary" id="id_edit_app_button" href="{% url 'oauth2_provider:update' application.pk %}">Edit</a>
        <button class="btn btn-danger" id="id_delete_app_button" data-toggle="modal" data-target="#confirmModal" data-modal-title="Delete" data-modal-body="<p>Are you sure you want to delete the app {{ application.name }}?</p><p>This action cannot be undone.</p>" data-form-action="{% url 'oauth2_provider:delete' application.pk %}">Delete</button>
      </div>
    </div>
  </div>
</div>
<div id="confirmModal" class="modal" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Placeholder title</h4>
      </div>
      <div class="modal-body">
        Placeholder body
      </div>
      <div class="modal-footer">
        <form method="post" action="" style="margin-bottom:0">
          {% csrf_token %}
          <input type="hidden" name="next" value="{% url 'settings' %}" />
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" id="id_delete_confirm_button" class="btn btn-primary btn-danger">Delete</button>
        </form>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endblock %}

src/templates/oauth2_provider/application_form.html
{% extends "layout.html" %}

{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <h4 class="inline-block">
        <a href="{% url 'browser-user' user.get_username %}">{{ user.get_username }}</a> / <a href="{% url 'browser-apps' %}">apps</a>
    </h4>

    <hr />
    <br />
    <form class="col-xs-12 col-sm-6 col-sm-offset-3" role="form" method="POST" action="{% block app-form-action-url %}{% url 'oauth2_provider:update' application.id %}{% endblock app-form-action-url %}">
        <h3 class="block-center-heading">
            {% block app-form-title %}
                Edit OAuth app {{ application.name }}
            {% endblock app-form-title %}
        </h3>
        {% csrf_token %}
        {{ form|crispy }}

        <div class="control-group">
            <div class="controls">
                <a class="btn btn-default" href="{% block app-form-back-url %}{% url 'oauth2_provider:detail' application.id %}{% endblock app-form-back-url %}">
                    Cancel
                </a>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </div>
    </form>
</div>
{% endblock %}

src/templates/oauth2_provider/application_registration_form.html
{% extends "oauth2_provider/application_form.html" %}

{% load i18n %}

{% block app-form-title %}{% trans "Register a new application" %}{% endblock app-form-title %}

{% block app-form-action-url %}{% url 'oauth2_provider:register' %}{% endblock app-form-action-url %}

{% block app-form-back-url %}{% url "oauth2_provider:list" %}"{% endblock app-form-back-url %}

src/templates/oauth2_provider/authorize.html
{% extends "bare-layout.html" %}

{% block content %}
    <div class="container">
        {% if not error %}
            <form class="col-xs-12 col-sm-6 col-sm-offset-3" id="authorizationForm" method="post">
                <h3 class="block-center-heading">Authorization Request</h3>
                {% csrf_token %}

                {% for field in form %}
                    {% if field.is_hidden %}
                        {{ field }}
                    {% endif %}
                {% endfor %}

                <br />

                <p>The application <strong><em>{{ application.name }}</em></strong> requests the following permissions:</p>
                <ul>
                    {% for scope in scopes_descriptions %}
                        <li>{{ scope }}</li>
                    {% endfor %}
                </ul>

                {{ form.errors }}
                {{ form.non_field_errors }}

                <br />

                <p>
                <input type="submit" class="btn btn-lg btn-default" value="Cancel"/>
                <input type="submit" class="btn btn-lg btn-primary" name="allow" value="Authorize"/>
                </p>

                <br />
                <p>Granted permissions typically expire after 24 hours. You can revoke granted permissions at any time from <a href="{% url 'settings' %}">account settings</a>.</p>
            </form>

        {% else %}
            <div class="col-xs-12 col-sm-6 col-sm-offset-3">
            <h3>Error: {{ error.error }}</h3>
            <p>{{ error.description }}</p>
            </div>
        {% endif %}
    </div>
{% endblock %}

src/templates/oauth2_provider/authorized-token-delete.html
{% extends "minimal-layout.html" %}

{% load i18n %}
{% load string_utils %}

{% block content %}
<div class="container">
    <form class="col-xs-12 col-sm-6 col-sm-offset-3" action="" role="form" method="POST">
        <h3>Revoke Access Token</h3>
        <br />
        {% csrf_token %}
        <p>{% trans "Are you sure you want to revoke this token?" %}</p>
        <input class="btn btn-lg btn-danger" type="submit" value="{% trans "Revoke" %}" />
    </form>
</div>
{% endblock %}

src/templates/oauth2_provider/authorized-tokens.html
{% extends "layout.html" %}

{% load string_utils %}

{% block content %}
<div class="container">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Granted OAuth Tokens</h3>
            </div>
            <ul class="list-group">
                {% for authorized_token in authorized_tokens %}
                    <li class="list-group-item">
                        <a class="btn btn-link pull-right" href="{% url 'oauth2_provider:authorized-token-delete' authorized_token.pk %}">Revoke</a>
                        <div>
                            <i class="fa fa-ticket fa-lg fa-fw"></i>&nbsp;{{ authorized_token.application }}
                            <br />
                            Scopes: {{ authorized_token.scopes.keys|joinand }}
                            <br />
                            Expires: {{ authorized_token.expires }}
                        </div>
                    </li>
                {% empty %}
                    <li class="list-group-item">No granted OAuth tokens.</li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}